### PR TITLE
adding specs and making some minor refactors - fixes #4

### LINKED ISSUE #4: Add specs to gem

### PR DESCRIPTION
**Pull request by saneshark**
@ayaleloehr This is probably ready for review, but I realized I forgot to set WebMock back to require localhost to also be stubbed as I did for /session I will probably want to create stubs for those endpoints as well as currently it would not work for you unless you run my branch of mock-prescription-api locally.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Via offline conversation, I know this is a work in progress, so going to assign back to you for now. @saneshark please assign to me when ready for review.

**Comment by saneshark** [comment]
@ayaleloehr I just tagged you and realized I need to upmerge with master and resolve conflicts

**Comment by saneshark** [comment]
@mphprogrammer I'm tagging you for code review on this PR when you have a moment.

**Comment by mphprogrammer** [comment]
LGTM

**Pull request merged**
